# Generated by Django 5.2 on 2025-04-26 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcategories',
            new_name='subcategory',
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL, verbose_name='Владелец корзины'),
        ),
        migrations.AlterField(
            model_name='basketitems',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.basket', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='basketitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_entries', to='main.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='basketitems',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество продуктов в корзине'),
        ),
    ]
